baseURL: https://intro-economia-2022.netlify.app
languageCode: en-us
title: Introducción a Econoomía
theme: hugo-serif-theme
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
params:
  colors:
    black: '#2f2f41'
    grey: '#5C5A5A'
    primary: '#004361'
    white: '#ffffff'
    white_offset: '#f6f7ff'
  fonts:
    base: Source Sans Pro
    google_fonts: https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap
    heading: Playfair Display
  footer:
    copyright_text: Una clase diseñada para El Colegio de la Frontera Norte programa MAPDS por <a class="zerostatic" href="https://insight4health.netlify.app/">José Luis Manzanares Rivera 
  google_analytics_id: ''
  google_tag_manager_id: ''
  homepage:
    show_contact_box: yes
    show_services_button: yes
  logo:
    alt: Bienvenido al Curso Introducción a la economía 
    desktop: images/logo/logoecon.svg
    desktop_height: 36px
    mobile: images/logo/logoecon.svg
    mobile_height: 36px
  seo:
    meta_og_image: https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
  team:
    summary_large_truncate: 120
menu:
  footer:
    - name: Bienvenida
      url: /
      weight: 1
    - name: Contacto
      url: /contact/
      weight: 2
  main:
    - name: Sesiones
      url: /services/
      weight: 1
    - name: Entregas
      url: /team/
      weight: 2
    - name: Recursos
      url: /about/
      weight: 3
    - name: Contacto
      url: /contact/
      weight: 4
